### ISSUE TITLE
Textul pentru HackDay#4 nu e actualizat

### ISSUE THREAD

**Issue by grigoroiualex** [code4romania/tfsg.code4.ro#7]
A fost trimis newsletter, dar pagina de înscriere încă vorbește depsre HackDay#4, care ar putea să inducă vizitatorii în eroare.

**Comment by overeha** [comment]
Please replace **this** 

Vino alături de noi pe 30 martie la a treia ediție de Hack Day al Code for Romania de anul acesta. Dacă ești din București, Timișoara, Cluj-Napoca sau Iași participă la unul dintre evenimentele locale ale comunității Code for Romania. Vino cu laptopul, conectează-te și codează la una dintre viitoarele aplicații care vor schimba România în bine. Dacă nu poți participa în niciunul dintre cele patru orașe, atunci poți să ni te alături online și să lucrezi de oriunde.

**with**

Vino alături de noi pe 20 martie la a patra ediție de Hack Day al Code for Romania de anul acesta. Dacă ești din București, Timișoara, Cluj-Napoca sau Iași participă la unul dintre evenimentele locale ale comunității Code for Romania. Vino cu laptopul, conectează-te și codează la una dintre viitoarele aplicații care vor schimba România în bine. Dacă nu poți participa în niciunul dintre cele patru orașe, atunci poți să ni te alături online și să lucrezi de oriunde.

Super important! HackDay #4 este o ediție super specială.
        ::     În primul rând, după cum poți vedea, va avea loc în penultima sâmbătă a lunii, ca să nu periclităm vacanța prelungită de Paște + 1 Mai :)
        ::     În al doilea rând, este ziua noastră așa că avem parte de program special! Aniversăm împreună 3 ani de Code for Romania și am pregătit o zi interesantă. Începem tot la 10, dar ziua va avea parte de multe surprize pe care ți le anunțăm cât de curând. Also, vor intra proiecte noi în development. Stay tuned!

**Comment by overeha** [comment]
For English

Join us on the 20th of April for our fourth monthly Code for Romania Hack Day for 2019. If you’re in Bucharest, Timișoara, Cluj-Napoca or Iași you can participate in-person at one of the Code for Romania local community events. Bring your laptop, get connected and start coding for one of the apps that will change Romania for the better! If you can’t join us in person in one of the four cities you can always join us online and work from home or from your favorite coffee shop!

Super important! HackDay #4 is a very special edition. 
:: First of all, as you can see, it will take place in the third weekend of the month so that we donțt jeopardize the Easter vacation :)
:: Second, it is our birthday, therefore we have a special schedule in place. We will celebrate our third anniversary together and we are preparing a very interesting day for you. We will start at 10 am, as usual, but there will be many surprises in store and new projects will enter development.
